export enum ErrorCode {
  // System & Standard HTTP Errors
  ERR_INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR',
  ERR_BAD_REQUEST = 'ERR_BAD_REQUEST',
  ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  ERR_FORBIDDEN = 'ERR_FORBIDDEN',
  ERR_NOT_FOUND = 'ERR_NOT_FOUND',
  ERR_CONFLICT = 'ERR_CONFLICT',
  ERR_UNPROCESSABLE_ENTITY = 'ERR_UNPROCESSABLE_ENTITY',
  ERR_RATE_LIMIT_EXCEEDED = 'ERR_RATE_LIMIT_EXCEEDED',
  ERR_PAYLOAD_TOO_LARGE = 'ERR_PAYLOAD_TOO_LARGE',
  ERR_SERVICE_UNAVAILABLE = 'ERR_SERVICE_UNAVAILABLE',
  ERR_UNKNOWN = 'ERR_UNKNOWN',

  // Validation & Database
  ERR_VALIDATION = 'ERR_VALIDATION',
  ERR_DB_VALIDATION = 'ERR_DB_VALIDATION',
  ERR_DUPLICATE_KEY = 'ERR_DUPLICATE_KEY',
  ERR_INVALID_ID = 'ERR_INVALID_ID',
  ERR_DB_CONNECTION = 'ERR_DB_CONNECTION',

  // Authentication & Authorization
  ERR_INVALID_CREDENTIALS = 'ERR_INVALID_CREDENTIALS',
  ERR_TOKEN_EXPIRED = 'ERR_TOKEN_EXPIRED',
  ERR_INVALID_TOKEN = 'ERR_INVALID_TOKEN',
  ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND',
  ERR_USER_INACTIVE = 'ERR_USER_INACTIVE',
  ERR_EMAIL_ALREADY_EXISTS = 'ERR_EMAIL_ALREADY_EXISTS',
  ERR_OTP_INVALID = 'ERR_OTP_INVALID',
  ERR_OTP_EXPIRED = 'ERR_OTP_EXPIRED',
  ERR_INSUFFICIENT_PERMISSIONS = 'ERR_INSUFFICIENT_PERMISSIONS',

  // Products & Categories
  ERR_PRODUCT_NOT_FOUND = 'ERR_PRODUCT_NOT_FOUND',
  ERR_CATEGORY_NOT_FOUND = 'ERR_CATEGORY_NOT_FOUND',
  ERR_INSUFFICIENT_STOCK = 'ERR_INSUFFICIENT_STOCK',
  ERR_INVALID_PRICE = 'ERR_INVALID_PRICE',

  // Cart & Checkout
  ERR_CART_NOT_FOUND = 'ERR_CART_NOT_FOUND',
  ERR_CART_ITEM_NOT_FOUND = 'ERR_CART_ITEM_NOT_FOUND',
  ERR_CART_EMPTY = 'ERR_CART_EMPTY',

  // Orders
  ERR_ORDER_NOT_FOUND = 'ERR_ORDER_NOT_FOUND',
  ERR_ORDER_INVALID_STATUS = 'ERR_ORDER_INVALID_STATUS',
  ERR_ORDER_CANCEL_FORBIDDEN = 'ERR_ORDER_CANCEL_FORBIDDEN',
  ERR_ORDER_ACCESS_DENIED = 'ERR_ORDER_ACCESS_DENIED',

  // Promotions & Vouchers
  ERR_VOUCHER_NOT_FOUND = 'ERR_VOUCHER_NOT_FOUND',
  ERR_VOUCHER_EXPIRED = 'ERR_VOUCHER_EXPIRED',
  ERR_VOUCHER_USAGE_LIMIT = 'ERR_VOUCHER_USAGE_LIMIT',
  ERR_VOUCHER_MIN_AMOUNT = 'ERR_VOUCHER_MIN_AMOUNT',

  // Payments
  ERR_PAYMENT_FAILED = 'ERR_PAYMENT_FAILED',
  ERR_PAYMENT_NOT_FOUND = 'ERR_PAYMENT_NOT_FOUND',
  ERR_PAYMENT_SIGNATURE_INVALID = 'ERR_PAYMENT_SIGNATURE_INVALID',

  // Inventory
  ERR_INVENTORY_NOT_FOUND = 'ERR_INVENTORY_NOT_FOUND',
  ERR_INVENTORY_NEGATIVE_STOCK = 'ERR_INVENTORY_NEGATIVE_STOCK',

  // Reviews
  ERR_REVIEW_NOT_FOUND = 'ERR_REVIEW_NOT_FOUND',
  ERR_REVIEW_FORBIDDEN = 'ERR_REVIEW_FORBIDDEN',
  ERR_REVIEW_UNVERIFIED_PURCHASE = 'ERR_REVIEW_UNVERIFIED_PURCHASE',
}
