import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, SchemaTypes } from 'mongoose';

export type LandingPageDocument = LandingPage & Document;

@Schema({ _id: false })
export class BenefitItem {
  @Prop({ required: true })
  title: string;

  @Prop()
  description: string;

  @Prop()
  icon: string;
}

@Schema({ _id: false })
export class PackageItem {
  @Prop({ required: true })
  name: string;

  @Prop({ required: true })
  price: number;

  @Prop()
  originalPrice: number;

  @Prop()
  badge: string;

  @Prop({ default: false })
  isBestSeller: boolean;
}

@Schema({ _id: false })
export class TestimonialItem {
  @Prop({ required: true })
  authorName: string;

  @Prop()
  avatar: string;

  @Prop({ required: true })
  content: string;

  @Prop({ default: 5 })
  rating: number;
}

@Schema({ timestamps: true })
export class LandingPage {
  @Prop({ required: true })
  title: string;

  @Prop({ required: true, unique: true })
  slug: string;

  @Prop()
  description: string;

  @Prop({ type: [String], default: [] })
  images: string[]; // Base64 or image URLs

  @Prop({ default: 30 })
  countdownMinutes: number;

  @Prop({ default: 0 })
  price: number;

  @Prop({ default: 0 })
  originalPrice: number;

  @Prop()
  badgeText: string;

  // Custom configuration generated by Gemini
  @Prop({ type: [BenefitItem], default: [] })
  benefits: BenefitItem[];

  @Prop({ type: [PackageItem], default: [] })
  packages: PackageItem[];

  @Prop({ type: [TestimonialItem], default: [] })
  testimonials: TestimonialItem[];

  @Prop({ type: String, default: '#dc2626' })
  primaryColor: string;

  @Prop({ type: String, default: '#fff' })
  backgroundColor: string;

  @Prop({ type: String, default: '#1e293b' })
  textColor: string;

  @Prop({ type: String })
  customCss: string;

  @Prop({ default: true })
  status: boolean;
}

export const LandingPageSchema = SchemaFactory.createForClass(LandingPage);
